Repository AY2223S2-CS2103-W16-4/tp, pull requests merged in 2023-04, with the labels that each got.

#143 Update user guide
  docs/UserGuide.md
Labels: documentation

#144 Remove remark from sort feature
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: bug

#145 Phone number bug fix
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: bug

#147 Bug fixes v1.4
  docs/UserGuide.md
  docs/images/Ui.png
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: bug, documentation

#149 Update evanpy.md
  docs/team/evanpy.md
Labels: documentation

#151 Fix Transaction
  src/main/java/seedu/address/logic/commands/txncommands/AddTxnCommand.java
  src/main/java/seedu/address/logic/commands/txncommands/DeleteTxnCommand.java
  src/main/java/seedu/address/logic/commands/txncommands/EditTxnCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/txncommandparser/DeleteTxnCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTxnCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTxnCommandTest.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
Labels: bug

#152 Clear command bugfix
  README.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: documentation

#179 v1.4 Bug Fixes for sort and edit commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: bug

#186 Add PPP, and more refinements to documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  docs/team/ajjajjajjajj.md
Labels: documentation

#187 Documentation 2
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: documentation

#190 Update DG TaskList
  docs/DeveloperGuide.md
  docs/diagrams/TaskListDiagram.puml
  docs/images/TaskListDiagram.png
  src/main/java/seedu/address/logic/commands/ClearTaskCommand.java
Labels: documentation

#193 Update UG to add examples for addtask and cleartask
  docs/UserGuide.md
Labels: documentation

#197 Update use cases and add 2 planned enhancements
  docs/DeveloperGuide.md
Labels: documentation

#203 Update ppp v1.4
  docs/team/benedict733.md
Labels: documentation
