Repository AY2223S2-CS2103-W16-4/tp, pull requests merged in 2023-03, with the labels that each got.

#20 Fix issues related to adaptation from AB3
  README.md
  docs/_config.yml
Labels: documentation

#24 Updated PPP and UG
  docs/UserGuide.md
  docs/team/johndoe.md
  docs/team/wesleybldc.md
Labels: documentation

#21 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#30 Tutorial adding command - Remark
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement, type.Story

#36 Lead status feature
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/StatusCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/status/LeadStatus.java
  src/main/java/seedu/address/model/person/status/LeadStatusName.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/StatusCommandTest.java
  src/test/java/seedu/address/logic/parser/StatusCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: enhancement, type.Story

#44 Transactions feature
  src/main/java/seedu/address/logic/commands/AddTxnCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/transaction/PersonTransactionMap.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/TxnStatus.java
  src/main/java/seedu/address/model/transaction/UniqueTransactionList.java
  src/main/java/seedu/address/model/transaction/UpdatedTransactionComparator.java
  src/main/java/seedu/address/model/transaction/exceptions/DuplicateTransactionException.java
  src/main/java/seedu/address/model/transaction/exceptions/NoPersonAssociatedException.java
  src/main/java/seedu/address/model/transaction/exceptions/TransactionNotFoundException.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement, type.Story

#46 Update UGv2
  build.gradle
  docs/UserGuide.md
Labels: documentation

#47 Update Transaction
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/txncommands/AddTxnCommand.java
  src/main/java/seedu/address/logic/commands/txncommands/DeleteTxnCommand.java
  src/main/java/seedu/address/logic/commands/txncommands/EditTxnCommand.java
  src/main/java/seedu/address/logic/commands/txncommands/ListTxnCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/txncommandparser/AddTxnCommandParser.java
  src/main/java/seedu/address/logic/parser/txncommandparser/DeleteTxnCommandParser.java
  src/main/java/seedu/address/logic/parser/txncommandparser/EditTxnCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/transaction/Description.java
  src/main/java/seedu/address/model/transaction/Owner.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/TxnStatus.java
  src/main/java/seedu/address/model/transaction/Value.java
  src/main/java/seedu/address/storage/JsonAdaptedTxn.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateTransactionAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidTransactionsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTransactionsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: documentation, type.Story

#65 Add sort functionality
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTxnCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: documentation, enhancement

#69 Update developer guide for sort feature
  docs/DeveloperGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: documentation

#76 Fix bugs introduced by new UI
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: bug, enhancement

#81 Change the industry field to location
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/StatusCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Industry.java
  src/main/java/seedu/address/model/person/Location.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#89 Update UG v1.3b
  docs/UserGuide.md
  docs/team/benedict733.md
Labels: documentation
